## Ejercicios Numpy 

#### 1. Crea una matriz 4*4 rellena con el valor 0.5

In [1]:
import numpy as np 
numero = 0.5 
size = 4
print(np.array([np.linspace(numero, numero, num=size)]*size))

print(np.ones((4,4))*0.5)
matrizEj1 = np.ones((4,4))*0.5

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


#### 2. Crea una matriz 6*6 con unos en los bordes y 0 en el interior (utilizando slicing)

In [2]:
num = 6

matriz = np.ones((num,num))*0
print(matriz)
matriz[0:num, 0] = 1
matriz[0, 0:num] = 1
matriz[num-1, 0:num] = 1
matriz[0:num, num-1] = 1
print("")
print(matriz)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 3. Crea una matriz de numpy 3*2 a partir de una lista de listas de números float

In [47]:
lista = [[2.233232,4.32323232],[5.32323232,5.3232424],[6.4434343,7.43434343]]

matriz2 = np.array(lista, dtype=np.float32)
print(matriz2)
print(len(matriz2))

[[2.233232  4.323232 ]
 [5.323232  5.323242 ]
 [6.4434342 7.4343433]]
3


#### 4. Divide entre 4 los valores de la columna 1

In [56]:
matriz2[:, 0] = matriz2[:, 0] / 4
print(matriz2)

[[0.558308  4.323232 ]
 [1.330808  5.323242 ]
 [1.6108586 7.4343433]]


#### 5. Calcula la media de los elementos de las primeras dos primeras filas

In [59]:
print(f"Media: {matriz2[:2].mean()}")

Media: 2.8838977813720703


#### 6. Crea una matriz aletoria de 4*4 con valores en [0, 1) 

El módulo <code>random</code> de numpy sirve para generar números aleatorios. En él tenemos varias funciones entre ellas <a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html">rand</a>



In [60]:
matrizAl = np.random.rand(4,4)
print(matrizAl)

[[0.97942235 0.65886994 0.46368199 0.99565715]
 [0.99578958 0.96383965 0.75516782 0.64339887]
 [0.35154572 0.03933426 0.12783771 0.89528632]
 [0.33422392 0.00351427 0.25342094 0.3137421 ]]


#### 7.  Muestra la suma, media y desviación de los elementos de la matriz del ejercicio 6 

In [62]:
print(f"Suma: {matrizAl.sum()}")
print(f"Media: {matrizAl.mean()}")
print(f"Desviación: {matrizAl.std():.3f}")

Suma: 8.774732576747954
Media: 0.5484207860467472
Desviación: 0.345


#### 8. Ordena por filas la matriz del ejercicio 6

In [63]:
print(np.sort(matrizAl))

[[0.46368199 0.65886994 0.97942235 0.99565715]
 [0.64339887 0.75516782 0.96383965 0.99578958]
 [0.03933426 0.12783771 0.35154572 0.89528632]
 [0.00351427 0.25342094 0.3137421  0.33422392]]


#### 9. Multiplica las matrices del ejercio 1 y 6

In [65]:
matrizExp = matrizEj1 * matrizAl
print(matrizExp)

[[0.48971117 0.32943497 0.23184099 0.49782858]
 [0.49789479 0.48191982 0.37758391 0.32169944]
 [0.17577286 0.01966713 0.06391886 0.44764316]
 [0.16711196 0.00175713 0.12671047 0.15687105]]


#### 10. Prueba a concatenar las matrices de los ejercicios 1 y 6 en vertical y horizontal

Echa un vistazo al apartado 2 del siguiente <a href="https://rmoralesdelgado.com/all/numpy-concatenate-r_-c_/"> link </a> donde explica el uso de <a href="https://numpy.org/doc/stable/reference/generated/numpy.c_.html">numpy.c_ </a> y <a href="https://numpy.org/doc/stable/reference/generated/numpy.r_.html">numpy.r_</a>

Fíjate también en <code>%%timeit</code> que se usa en Jupyter notebooks para medir el tiempo de ejecución de un bloque de código

In [68]:
print(np.r_[matrizEj1, matrizAl])
print(np.c_[matrizEj1, matrizAl])

[[0.5        0.5        0.5        0.5       ]
 [0.5        0.5        0.5        0.5       ]
 [0.5        0.5        0.5        0.5       ]
 [0.5        0.5        0.5        0.5       ]
 [0.97942235 0.65886994 0.46368199 0.99565715]
 [0.99578958 0.96383965 0.75516782 0.64339887]
 [0.35154572 0.03933426 0.12783771 0.89528632]
 [0.33422392 0.00351427 0.25342094 0.3137421 ]]
[[0.5        0.5        0.5        0.5        0.97942235 0.65886994
  0.46368199 0.99565715]
 [0.5        0.5        0.5        0.5        0.99578958 0.96383965
  0.75516782 0.64339887]
 [0.5        0.5        0.5        0.5        0.35154572 0.03933426
  0.12783771 0.89528632]
 [0.5        0.5        0.5        0.5        0.33422392 0.00351427
  0.25342094 0.3137421 ]]
