## Ejercicios Numpy 

#### 1. Crea una matriz 4*4 rellena con el valor 0.5

In [83]:
import numpy as np 
numero = 0.5 
size = 4
print(np.array([np.linspace(numero, numero, num=size)]*size))

print(np.ones((4,4))*0.5)
matrizEj1 = np.ones((4,4))*0.5

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


#### 2. Crea una matriz 6*6 con unos en los bordes y 0 en el interior (utilizando slicing)

In [41]:
num = 6

matriz = np.ones((num,num))*0
print(matriz)
matriz[0:num, 0] = 1
matriz[0, 0:num] = 1
matriz[num-1, 0:num] = 1
matriz[0:num, num-1] = 1
print("")
print(matriz)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 3. Crea una matriz de numpy 3*2 a partir de una lista de listas de números float

In [63]:
lista = [[2.233232,4.32323232],[5.32323232,5.3232424],[6.4434343,7.43434343]]

matriz2 = np.array(lista, dtype=np.float32)
print(matriz2)
print(len(matriz2))

[[2.233232  4.323232 ]
 [5.323232  5.323242 ]
 [6.4434342 7.4343433]]
3


#### 4. Divide entre 4 los valores de la columna 1

In [ ]:
matriz2[0, 0:len(matriz2[0])] = matriz2[0, 0:len(matriz2[0])] / 4
print(matriz2)

[[0.139577  0.270202 ]
 [5.323232  5.323242 ]
 [6.4434342 7.4343433]]
[[5.323232  5.323242 ]
 [6.4434342 7.4343433]]


#### 5. Calcula la media de los elementos de las primeras dos primeras filas

In [ ]:
print(f"Media: {matriz2[1:].mean()}")

Media: 6.131062984466553


#### 6. Crea una matriz aletoria de 4*4 con valores en [0, 1) 

El módulo <code>random</code> de numpy sirve para generar números aleatorios. En él tenemos varias funciones entre ellas <a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html">rand</a>



In [80]:
matrizAl = np.random.rand(4,4)
print(matrizAl)

[[0.22280212 0.63438165 0.19392997 0.88948171]
 [0.88772159 0.86332884 0.54509434 0.8993722 ]
 [0.97820145 0.3943093  0.43000198 0.29719841]
 [0.94011001 0.72003306 0.75319116 0.10145373]]


#### 7.  Muestra la suma, media y desviación de los elementos de la matriz del ejercicio 6 

In [81]:
print(f"Suma: {matrizAl.sum()}")
print(f"Media: {matrizAl.mean()}")
print(f"Desviación: {matrizAl.std():.3f}")

Suma: 9.750611518098701
Media: 0.6094132198811688
Desviación: 0.290


#### 8. Ordena por filas la matriz del ejercicio 6

In [82]:
print(np.sort(matrizAl))

[[0.19392997 0.22280212 0.63438165 0.88948171]
 [0.54509434 0.86332884 0.88772159 0.8993722 ]
 [0.29719841 0.3943093  0.43000198 0.97820145]
 [0.10145373 0.72003306 0.75319116 0.94011001]]


#### 9. Multiplica las matrices del ejercio 1 y 6

In [84]:
matrizExp = matrizEj1 * matrizAl
print(matrizExp)

[[0.11140106 0.31719083 0.09696499 0.44474086]
 [0.44386079 0.43166442 0.27254717 0.4496861 ]
 [0.48910072 0.19715465 0.21500099 0.14859921]
 [0.47005501 0.36001653 0.37659558 0.05072686]]


#### 10. Prueba a concatenar las matrices de los ejercicios 1 y 6 en vertical y horizontal

Echa un vistazo al apartado 2 del siguiente <a href="https://rmoralesdelgado.com/all/numpy-concatenate-r_-c_/"> link </a> donde explica el uso de <a href="https://numpy.org/doc/stable/reference/generated/numpy.c_.html">numpy.c_ </a> y <a href="https://numpy.org/doc/stable/reference/generated/numpy.r_.html">numpy.r_</a>

Fíjate también en <code>%%timeit</code> que se usa en Jupyter notebooks para medir el tiempo de ejecución de un bloque de código

In [86]:
print(np.r_[matrizEj1, matrizAl])
print(np.c_[matrizEj1, matrizAl])

[[0.5        0.5        0.5        0.5       ]
 [0.5        0.5        0.5        0.5       ]
 [0.5        0.5        0.5        0.5       ]
 [0.5        0.5        0.5        0.5       ]
 [0.22280212 0.63438165 0.19392997 0.88948171]
 [0.88772159 0.86332884 0.54509434 0.8993722 ]
 [0.97820145 0.3943093  0.43000198 0.29719841]
 [0.94011001 0.72003306 0.75319116 0.10145373]]
[[0.5        0.5        0.5        0.5        0.22280212 0.63438165
  0.19392997 0.88948171]
 [0.5        0.5        0.5        0.5        0.88772159 0.86332884
  0.54509434 0.8993722 ]
 [0.5        0.5        0.5        0.5        0.97820145 0.3943093
  0.43000198 0.29719841]
 [0.5        0.5        0.5        0.5        0.94011001 0.72003306
  0.75319116 0.10145373]]
